version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "16:55"
    timezone: "Europe/Oslo"
  target-branch: main
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "16:55"
    timezone: "Europe/Oslo"
  target-branch: 1.x
